apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: ns-env-provider
spec:
  # In-cluster Service URL for the External Data Provider (HTTP)
  url: http://external-data.provider-system.svc:8080/lookup
  timeout: 3
