apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NsEnvMatch
metadata:
  name: ns-env-match
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    excludedNamespaces:
      - kube-system
      - kube-public
      - kube-node-lease
      - gatekeeper-system
      - provider-system
      - default
