apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictHostNetwork
metadata:
  name: restrict-hostnetwork
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
