apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: provider-system
  labels:
    app: redis
    owner: mvp
    env: dev
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: provider-system
  labels:
    app: redis
    owner: mvp
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        owner: mvp
        env: dev
    spec:
      containers:
        - name: redis
          image: redis:7.2.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
