apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: provider-system
  labels:
    app: localstack
    owner: mvp
    env: dev
spec:
  ports:
    - name: http
      port: 4566
      targetPort: 4566
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: provider-system
  labels:
    app: localstack
    owner: mvp
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
        owner: mvp
        env: dev
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:2.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "s3,iam,sts"
            - name: DEBUG
              value: "0"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
