apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-data
  namespace: provider-system
  labels:
    app: external-data
    owner: mvp
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-data
  template:
    metadata:
      labels:
        app: external-data
        owner: mvp
        env: dev
    spec:
      containers:
        - name: external-data
          image: ghcr.io/rethick-jeganathan/opa-mvp-monorepo/external-data:week2-1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8443
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
