name: Build Policy Bundles

on:
  push:
    branches: [ main ]
    paths:
      - 'policy/**'
      - '.github/workflows/build-policy-bundles.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          ./opa version

      - name: Build bundle
        run: ./opa build -b policy -o policy-bundle.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: policy-bundle
          path: policy-bundle.tar.gz

      - name: Setup ORAS
        uses: oras-project/setup-oras@v1

      - name: Ensure jq present
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare publish variables
        id: vars
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO="${{ github.event.repository.name }}"
          TAG="main-${{ github.run_number }}"
          REF="ghcr.io/${OWNER_LOWER}/${REPO}/opa-bundles:${TAG}"
          echo "owner=${OWNER_LOWER}" >> $GITHUB_OUTPUT
          echo "repo=${REPO}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "ref=${REF}" >> $GITHUB_OUTPUT

      - name: Publish policy bundle to GHCR (ORAS)
        id: publish
        run: |
          REF="${{ steps.vars.outputs.ref }}"
          echo "Pushing to $REF"
          oras push "$REF" \
            policy-bundle.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip \
            --annotation org.opencontainers.image.title=policy-bundle.tar.gz \
            --annotation org.opencontainers.image.revision=${{ github.sha }}
          DIGEST=$(oras manifest fetch --descriptor "$REF" | jq -r '.digest')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "Pushed: $REF@$DIGEST"

      - name: Summary (GHCR reference)
        run: |
          echo "### Policy Bundle Published to GHCR" >> $GITHUB_STEP_SUMMARY
          echo "- Ref: oci://${{ steps.vars.outputs.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tag: ${{ steps.vars.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- Digest: ${{ steps.publish.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
          echo "- Workflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
